### ISSUE TITLE
Error in plugin CR-10 Leveling with DashBorad :

### ISSUE THREAD

**Issue by theos10** [j7126/OctoPrint-Dashboard#318]
HI,

I have CR10-pluging leveling in dashboard.
When in clic on button, nothing's happening

I have this log : 
2021-11-21 19:02:30,119 - octoprint.util.comm - ERROR - Error while processing hook dashboard for phase sending and command G0 Z0F500:
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 4611, in _process_command_phase
    tags=tags,
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_dashboard/__init__.py", line 811, in process_gcode
    CmdDict = dict ((x,float(y)) for d,x,y in (re.split('([A-Z])', i) for i in cmd.upper().split()))
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_dashboard/__init__.py", line 811, in <genexpr>
    CmdDict = dict ((x,float(y)) for d,x,y in (re.split('([A-Z])', i) for i in cmd.upper().split()))
ValueError: too many values to unpack (expected 3)

Thank you for your help.

**Comment by j7126** [comment]
Not sure how I missed this issue, however looks like it did get fixed back in December https://github.com/lsellens/OctoPrint-Cr10_leveling/issues/34

I will try to make dashboard's gcode processing more resilient so that this can't happen with other plugins.
